# Generated by Django 5.0.6 on 2024-07-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0002_jobmodel_createdby_recruitersmodel_jobuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='CreatedBy',
            new_name='Created_By',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='JobDescription',
            new_name='Job_Description',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='NumberOfOpenings',
            new_name='Number_Of_Openings',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='SkillsSet',
            new_name='Skills_Set',
        ),
    ]
