# Generated by Django 5.0.6 on 2024-07-08 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0004_jobapplymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplymodel',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobapply', to='JobPortalApp.jobmodel'),
        ),
    ]
